/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlMenuPrincipal;

/**
 *
 * @author Bryan
 */
public class panelAmarillo extends javax.swing.JPanel {

    /**
     * Creates new form panelAmarillo
     */
    public panelAmarillo() {
        initComponents();
       
    }
    
    public static void initAmarillo(){
            
        panelRojo panel = new panelRojo();
        frmMenuPrincipal vista = new frmMenuPrincipal();
        panelAmarillo panel2 = new panelAmarillo();
        
        ctrlMenuPrincipal controlador = new ctrlMenuPrincipal(vista,panel, panel2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDespedirse = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 51));

        btnDespedirse.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnDespedirse)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(btnDespedirse)
                .addGap(219, 219, 219))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDespedirse;
    // End of variables declaration//GEN-END:variables
}
